services:
  server:
    build: ./BackEnd
    ports:
      - "8000:8000"
    env_file:
      - ./BackEnd/.env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - my_network
    volumes:
      - ./BackEnd/.wwebjs_auth:/app/.wwebjs_auth
      - ./BackEnd/.wwebjs_cache:/app/.wwebjs_cache
      - ./BackEnd/messages.db:/app/messages.db

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    networks:
     - my_network
  
  app:
    build: ./FrontEnd
    ports:
      - "3000:3000"
    env_file:
      - ./FrontEnd/.env
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
